# tasks file
---
- import_tasks: version-support.yml
  tags:
    - configuration
    - percona-client
    - percona-client-version-support

- import_tasks: repository.yml
  tags:
    - configuration
    - percona-client
    - percona-client-repository

- import_tasks: install.yml
  tags:
    - configuration
    - percona-client
    - percona-client-install

- import_tasks: configure.yml
  tags:
    - configuration
    - percona-client
    - percona-client-configure
